data_paths:
  source_directory: "./data/papers"
  output_directory: "./data/text"
  chunks_directory: "./data/chunks"
  cache_directory: "./data/cache"

processing:
  chunk_size: 1500
  chunk_overlap: 200
  batch_size: 50
  timeout_seconds: 300

web_interface:
  port: 8001
  host: "localhost"
  cache_ttl: 300

logging:
  level: "INFO"
  log_to_file: true
  log_file: "./logs/test.log"