# AI Portfolio Optimizer Configuration for External Ontology Workflow
# Configuration compliant with config_schema.json

# Data paths (required)
data_paths:
  source_directory: "./data/papers"
  output_directory: "./data/output"
  chunks_directory: "./data/chunks"
  cache_directory: "./data/cache"

# Processing configuration
processing:
  chunk_size: 1500
  chunk_overlap: 150
  batch_size: 50
  timeout_seconds: 300

# Concept extraction configuration
concept_extraction:
  enabled: true
  min_frequency: 2
  max_concepts_per_chunk: 20
  confidence_threshold: 0.6

# External knowledge configuration
external_knowledge:
  enabled: true
  dbpedia:
    enabled: true
    endpoint: "https://dbpedia.org/sparql"
    timeout: 30
  wikidata:
    enabled: true
    endpoint: "https://query.wikidata.org/sparql"
    timeout: 30
  cache:
    enabled: true
    max_size: 10000
    ttl_hours: 168

# Graph database configuration
graph_database:
  enabled: true
  neo4j:
    uri: "neo4j://localhost:7687"
    username: "neo4j"
    password: "password"
    database: "neo4j"
  timeout_seconds: 30

# Logging configuration
logging:
  level: "INFO"
  file_enabled: true
  file_path: "./logs/workflow.log"

# Optional API keys (set via environment variables)
api_keys:
  openai: ""
  mathpix: ""
  pinecone: ""